// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: general.sql

package sqlc

import (
	"context"

	null "gopkg.in/guregu/null.v4"
)

const getNamesByIds = `-- name: GetNamesByIds :one
SELECT "name" AS "pocket_name"
FROM "pocket" p
WHERE p."salesforce_id" = $1
UNION
SELECT "name" AS "currency_name"
FROM "currencies" c
WHERE c."id" = $2
UNION
SELECT "operation_name" AS "operation_name"
FROM "operation" o
WHERE o."id" = $3
UNION
SELECT "user_id" AS "user_id"
FROM "pocket" pp
WHERE pp."salesforce_id" = $1
`

type GetNamesByIdsParams struct {
	PocketID    null.String `json:"pocket_id"`
	CurrencyID  int32       `json:"currency_id"`
	OperationID string      `json:"operation_id"`
}

func (q *Queries) GetNamesByIds(ctx context.Context, arg GetNamesByIdsParams) (null.String, error) {
	row := q.db.QueryRow(ctx, getNamesByIds, arg.PocketID, arg.CurrencyID, arg.OperationID)
	var pocket_name null.String
	err := row.Scan(&pocket_name)
	return pocket_name, err
}
